name: App Simples

deploy:
  needs: build
  runs-on: ubuntu-latest
  steps:
    - name: deploy via ssh (appleboy)
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd ~
          if [ ! -d "zamengo-app" ]; then
            git clone https://github.com/${{ github.repository }} zamengo-app
          fi
          cd zamengo-app
          git pull origin main
          docker compose pull
          docker compose up -d